/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as VeiculosIdRouteImport } from './routes/veiculos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosIdRoute = VeiculosIdRouteImport.update({
  id: '/veiculos/$id',
  path: '/veiculos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipes' | '/veiculos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipes' | '/veiculos/$id'
  id: '__root__' | '/' | '/equipes' | '/veiculos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipesRoute: typeof EquipesRoute
  VeiculosIdRoute: typeof VeiculosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/$id': {
      id: '/veiculos/$id'
      path: '/veiculos/$id'
      fullPath: '/veiculos/$id'
      preLoaderRoute: typeof VeiculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipesRoute: EquipesRoute,
  VeiculosIdRoute: VeiculosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
