/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RiscoRouteImport } from './routes/risco'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VeiculosIdRouteImport } from './routes/veiculos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RiscoRoute = RiscoRouteImport.update({
  id: '/risco',
  path: '/risco',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosIdRoute = VeiculosIdRouteImport.update({
  id: '/veiculos/$id',
  path: '/veiculos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risco': typeof RiscoRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risco': typeof RiscoRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risco': typeof RiscoRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipes'
    | '/reset-password'
    | '/risco'
    | '/usuarios'
    | '/veiculos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipes'
    | '/reset-password'
    | '/risco'
    | '/usuarios'
    | '/veiculos/$id'
  id:
    | '__root__'
    | '/'
    | '/equipes'
    | '/reset-password'
    | '/risco'
    | '/usuarios'
    | '/veiculos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipesRoute: typeof EquipesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiscoRoute: typeof RiscoRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosIdRoute: typeof VeiculosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risco': {
      id: '/risco'
      path: '/risco'
      fullPath: '/risco'
      preLoaderRoute: typeof RiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/$id': {
      id: '/veiculos/$id'
      path: '/veiculos/$id'
      fullPath: '/veiculos/$id'
      preLoaderRoute: typeof VeiculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipesRoute: EquipesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RiscoRoute: RiscoRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosIdRoute: VeiculosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
