CREATE TABLE public.equipes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), nome text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.veiculos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), placa text NOT NULL, cor text, modelo text, rastreado boolean NOT NULL DEFAULT false, km_inicial integer NOT NULL DEFAULT 0, km_atual integer NOT NULL DEFAULT 0, km_mensal_contratado integer, valor_contrato numeric, inicio_contrato date, fim_contrato date, condicoes text, cobertura_seguro text, intervalo_oleo_km integer DEFAULT 10000, intervalo_pneu_km integer DEFAULT 40000, equipe_id uuid REFERENCES public.equipes(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.historico_equipes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), veiculo_id uuid NOT NULL REFERENCES public.veiculos(id) ON DELETE CASCADE, equipe_id uuid REFERENCES public.equipes(id) ON DELETE SET NULL, data_inicio date NOT NULL DEFAULT current_date, data_fim date, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.leituras_km (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), veiculo_id uuid NOT NULL REFERENCES public.veiculos(id) ON DELETE CASCADE, mes date NOT NULL, km integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (veiculo_id, mes));
CREATE TABLE public.manutencoes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), veiculo_id uuid NOT NULL REFERENCES public.veiculos(id) ON DELETE CASCADE, tipo text NOT NULL CHECK (tipo IN ('oleo','pneu','mecanica','avaria')), data date NOT NULL DEFAULT current_date, km integer, descricao text, custo numeric, proximo_km integer, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.sinistros (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), veiculo_id uuid NOT NULL REFERENCES public.veiculos(id) ON DELETE CASCADE, data date NOT NULL DEFAULT current_date, motorista text, relato text, detalhamento text, envolvidos text, created_at timestamptz NOT NULL DEFAULT now());
DO $$ DECLARE t text; BEGIN
FOREACH t IN ARRAY ARRAY['equipes','veiculos','historico_equipes','leituras_km','manutencoes','sinistros'] LOOP
EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
EXECUTE format('CREATE POLICY "owner_all" ON public.%I FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)', t);
END LOOP; END $$;